platform:
  accel: 'gpu'
  thermompnn_dir: '/content/DetergentMPNN'

data_loc:
        megascale_csv: 'DetergentMPNN/data/dummy.csv'
        megascale_splits: 'DetergentMPNN/data/dummy_splits.pkl'
        megascale_pdbs: 'DetergentMPNN/examples/pdbs'

        fireprot_csv: 'C:\Users\marius\PycharmProjects\DetergentMPNN\data\fireprot\4_fireprotDB_bestpH.csv'
        fireprot_splits: 'C:\Users\marius\PycharmProjects\DetergentMPNN\thermompnn\datasets\splits\fireprot_splits.pkl'
        fireprot_pdbs: 'C:\Users\marius\PycharmProjects\DetergentMPNN\data\fireprot\pdbs\monomers'

        misc_data: 'C:\Users\marius\PycharmProjects\DetergentMPNN\data\'
        rosetta_data: '\home\hdieckhaus\datasets\FINAL_results\'
